#!/usr/bin/env python3
"""DO test: incompressibility checks for mean, modes, and realization fields.

Checks:
- Mean field divergence on post-transient window.
- Mode divergence diagnostic on interpolated grid.
- Optional sampled realization divergence on post-transient window.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

if __package__ is None or __package__ == "":
    sys.path.append(str(Path(__file__).resolve().parents[2]))
    from py_utils.common import (
        close_data,
        divergence_2d,
        l2_norm,
        load_data,
        normalize_time_axis,
        read_array,
    )
    from py_utils.tests.test_common import summarize_check, write_json_report
else:
    from ..common import close_data, divergence_2d, l2_norm, load_data, normalize_time_axis, read_array
    from .test_common import summarize_check, write_json_report


def _grid_spacing(x: np.ndarray, y: np.ndarray) -> tuple[float, float]:
    dx = float(np.mean(np.diff(x[0, :])))
    dy = float(np.mean(np.diff(y[:, 0])))
    if dx <= 0 or dy <= 0:
        raise ValueError(f"Invalid grid spacing: dx={dx}, dy={dy}")
    return dx, dy


def _realization_divergence(
    u_mean_t,
    v_mean_t,
    mode_u_t,
    mode_v_t,
    yi_t,
    dx,
    dy,
    max_samples,
    skip_first,
):
    nt = min(u_mean_t.shape[0], mode_u_t.shape[0], yi_t.shape[0])
    npart = yi_t.shape[1]
    t_start = min(max(0, int(skip_first)), max(0, nt - 1))
    nt_eff = max(1, nt - t_start)
    sample_t = np.linspace(t_start, nt - 1, num=min(max_samples, nt_eff), dtype=int)
    sample_p = np.linspace(0, npart - 1, num=min(max_samples, npart), dtype=int)
    vals = []
    for t_idx in sample_t:
        for p_idx in sample_p:
            u_r = u_mean_t[t_idx] + np.einsum("s,sxy->xy", yi_t[t_idx, p_idx], mode_u_t[t_idx])
            v_r = v_mean_t[t_idx] + np.einsum("s,sxy->xy", yi_t[t_idx, p_idx], mode_v_t[t_idx])
            vals.append(l2_norm(divergence_2d(u_r, v_r, dx, dy)))
    return float(np.max(vals) if vals else 0.0), float(np.median(vals) if vals else 0.0)


def _tail_slice(n: int, skip_first: int, tail_frac: float) -> slice:
    start = min(max(0, skip_first), max(0, n - 1))
    n_tail = max(1, int(round((n - start) * tail_frac)))
    return slice(max(start, n - n_tail), n)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data", type=Path, required=True, help="NPZ/HDF5 generated by py_utils/load_chk.py")
    ap.add_argument("--mean-thresh", type=float, default=5.0e-4)
    ap.add_argument("--mode-thresh", type=float, default=1.0e-1)
    ap.add_argument("--realization-thresh", type=float, default=5.0e-4)
    ap.add_argument("--skip-first", type=int, default=1, help="Ignore first N snapshots as startup transient")
    ap.add_argument("--tail-frac", type=float, default=0.8, help="Tail fraction for post-transient checks")
    ap.add_argument(
        "--enforce-mode-divergence",
        action="store_true",
        help="Fail if interpolated mode divergence exceeds threshold (diagnostic-only otherwise).",
    )
    ap.add_argument("--max-samples", type=int, default=6, help="Max random-like samples per axis for realization checks")
    ap.add_argument("--report-json", type=Path, default=None)
    args = ap.parse_args()
    if not (0.1 <= args.tail_frac <= 1.0):
        raise ValueError("--tail-frac must be in [0.1, 1.0]")

    data = load_data(args.data)
    try:
        x = read_array(data, "x")
        y = read_array(data, "y")
        u = normalize_time_axis(read_array(data, "u"), kind="spatial_time")
        v = normalize_time_axis(read_array(data, "v"), kind="spatial_time")
        dx, dy = _grid_spacing(x, y)

        div_mean = divergence_2d(u, v, dx, dy)
        mean_l2_t = np.sqrt(np.mean(div_mean * div_mean, axis=(1, 2)))
        mean_tail = _tail_slice(mean_l2_t.size, args.skip_first, args.tail_frac)
        mean_l2_med_tail = float(np.median(mean_l2_t[mean_tail]))
        mean_pass = mean_l2_med_tail <= args.mean_thresh

        checks = [
            summarize_check(
                "mean_incompressibility",
                mean_pass,
                {
                    "median_l2_divergence_tail": mean_l2_med_tail,
                    "max_l2_divergence_tail": float(np.max(mean_l2_t[mean_tail])),
                    "median_l2_divergence_full": float(np.median(mean_l2_t)),
                    "max_l2_divergence_full": float(np.max(mean_l2_t)),
                    "skip_first": int(args.skip_first),
                    "tail_frac": float(args.tail_frac),
                    "threshold": args.mean_thresh,
                },
            )
        ]

        if "mode_u" in data and "mode_v" in data:
            mode_u = normalize_time_axis(read_array(data, "mode_u"), kind="modes_spatial_time")
            mode_v = normalize_time_axis(read_array(data, "mode_v"), kind="modes_spatial_time")

            nmode = mode_u.shape[1]
            mode_l2 = np.zeros(nmode, dtype=float)
            for s in range(nmode):
                mode_l2[s] = l2_norm(divergence_2d(mode_u[:, s], mode_v[:, s], dx, dy))
            mode_med = float(np.median(mode_l2)) if nmode > 0 else 0.0
            mode_max = float(np.max(mode_l2)) if nmode > 0 else 0.0
            checks.append(
                summarize_check(
                    "mode_incompressibility",
                    (mode_med <= args.mode_thresh) if args.enforce_mode_divergence else True,
                    {
                        "max_mode_l2_divergence": mode_max,
                        "median_mode_l2_divergence": mode_med,
                        "n_modes": int(nmode),
                        "threshold": args.mode_thresh,
                        "enforced": bool(args.enforce_mode_divergence),
                    },
                )
            )

            if "yi" in data:
                yi = np.asarray(data["yi"])
                if yi.ndim != 3:
                    raise ValueError(f"Expected yi shape (P,S,T), got {yi.shape}")
                yi_t = np.transpose(yi, (2, 0, 1))
                real_max, real_med = _realization_divergence(
                    u,
                    v,
                    mode_u,
                    mode_v,
                    yi_t,
                    dx,
                    dy,
                    max_samples=max(1, args.max_samples),
                    skip_first=args.skip_first,
                )
                checks.append(
                    summarize_check(
                        "realization_incompressibility",
                        real_med <= args.realization_thresh,
                        {
                            "max_l2_divergence": real_max,
                            "median_l2_divergence": real_med,
                            "threshold": args.realization_thresh,
                        },
                    )
                )

        passed = all(c["passed"] for c in checks)
        payload = {
            "test": "do_incompressible_ns_test",
            "passed": passed,
            "checks": checks,
            "data": str(args.data),
        }
        print(json.dumps(payload, indent=2))
        write_json_report(args.report_json, payload)
        return 0 if passed else 2
    finally:
        close_data(data)


if __name__ == "__main__":
    raise SystemExit(main())
