#!/usr/bin/env python3
"""Generate vortex IC sample .fld files + DO manifest.

Workflow:
1) sample Lamb-Oseen parameters
2) write per-sample .pts using eval_ic_on_mesh.py
3) convert .pts -> .fld via FieldConvert pointdatatofld
4) write manifest listing generated .fld files
"""

from __future__ import annotations

import argparse
import os
import subprocess
from pathlib import Path
import numpy as np


def _run(cmd: list[str]) -> None:
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(
            f"Command failed: {' '.join(cmd)}\n"
            f"stdout:\n{proc.stdout}\n"
            f"stderr:\n{proc.stderr}"
        )


def main() -> int:
    root = Path(__file__).resolve().parents[3]
    ic_dir = Path(__file__).resolve().parent

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--n-samples", type=int, default=64)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--gamma", type=float, default=10.0)
    ap.add_argument("--radius-mean", type=float, default=0.2)
    ap.add_argument("--radius-std", type=float, default=0.1)
    ap.add_argument("--radius-min", type=float, default=0.01)
    ap.add_argument("--x0", type=float, default=np.pi)
    ap.add_argument("--y0", type=float, default=np.pi)
    ap.add_argument("--mesh-pts", type=Path, default=ic_dir / "mesh_pts.pts")
    ap.add_argument("--case-xml", type=Path, default=root / "cases/vortex/templates/casefile.xml")
    ap.add_argument("--fieldconvert", type=Path, default=root / "build/dist/bin/FieldConvert")
    ap.add_argument("--samples-dir", type=Path, default=ic_dir / "samples")
    ap.add_argument("--manifest", type=Path, default=ic_dir / "do_init_samples.txt")
    ap.add_argument("--keep-pts", action="store_true")
    args = ap.parse_args()

    if args.n_samples <= 0:
        raise ValueError("--n-samples must be > 0")

    args.samples_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(args.seed)

    eval_script = ic_dir / "eval_ic_on_mesh.py"
    fld_files: list[Path] = []

    for i in range(args.n_samples):
        radius = max(args.radius_min, float(rng.normal(args.radius_mean, args.radius_std)))
        pts_path = args.samples_dir / f"sample_{i:04d}.pts"
        fld_path = args.samples_dir / f"sample_{i:04d}.fld"

        _run(
            [
                "python3",
                str(eval_script),
                str(args.mesh_pts),
                str(pts_path),
                "--gamma",
                str(args.gamma),
                "--radius",
                str(radius),
                "--x0",
                str(args.x0),
                "--y0",
                str(args.y0),
            ]
        )

        _run(
            [
                str(args.fieldconvert),
                "-m",
                f"pointdatatofld:frompts={pts_path}",
                str(args.case_xml),
                str(fld_path),
            ]
        )

        if not args.keep_pts:
            pts_path.unlink(missing_ok=True)

        fld_files.append(fld_path)

    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    with args.manifest.open("w", encoding="utf-8") as f:
        f.write("# DO init IC sample files (.fld), one per line\n")
        f.write("# Generated by ic/generate_do_ic_samples.py\n")
        for p in fld_files:
            rel = os.path.relpath(p.resolve(), start=args.manifest.parent.resolve())
            f.write(f"{Path(rel).as_posix()}\n")

    print(f"Generated {len(fld_files)} IC samples in {args.samples_dir}")
    print(f"Manifest: {args.manifest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
