from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path

import numpy as np


def read_mesh_pts_xml(path: Path) -> dict[str, np.ndarray]:
    xs: list[float] = []
    ys: list[float] = []
    zs: list[float] = []
    in_pts = False
    dim = 2
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if "<POINTS" in line:
                in_pts = True
                m = re.search(r'DIM\s*=\s*"(\d+)"', line)
                if m:
                    try:
                        dim = int(m.group(1))
                    except ValueError:
                        dim = 2
                continue
            if "</POINTS>" in line:
                break
            if not in_pts:
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            xs.append(float(parts[0]))
            ys.append(float(parts[1]))
            if len(parts) >= 3:
                try:
                    zs.append(float(parts[2]))
                except ValueError:
                    zs.append(0.0)
            else:
                zs.append(0.0)

    if not xs:
        raise RuntimeError(f"No points found in {path}")

    return {
        "x": np.asarray(xs, dtype=float),
        "y": np.asarray(ys, dtype=float),
        "z": np.asarray(zs, dtype=float),
        "dim": np.asarray([dim], dtype=int),
    }


def write_pts_fields(path: Path, coords: dict[str, np.ndarray], fields: dict[str, np.ndarray], field_order: list[str]) -> None:
    x = np.asarray(coords["x"], dtype=float)
    y = np.asarray(coords["y"], dtype=float)
    z = np.asarray(coords.get("z", np.zeros_like(x)), dtype=float)
    dim_arr = np.asarray(coords.get("dim", np.asarray([2], dtype=int)))
    dim = int(dim_arr[0]) if dim_arr.size > 0 else 2
    if dim not in (2, 3):
        raise ValueError(f"Unsupported POINTS DIM={dim}; expected 2 or 3")
    npts = x.size

    arrays: list[np.ndarray] = []
    for key in field_order:
        if key not in fields:
            raise KeyError(f"Missing field '{key}' from profile evaluate_fields output")
        arr = np.asarray(fields[key], dtype=float)
        if arr.shape != (npts,):
            raise ValueError(f"Field '{key}' must have shape ({npts},), got {arr.shape}")
        arrays.append(arr)

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write('<?xml version="1.0" encoding="utf-8" ?>\n')
        f.write("<NEKTAR>\n")
        f.write(f'  <POINTS DIM="{dim}" FIELDS="{",".join(field_order)}">\n')
        for i in range(npts):
            vals = " ".join(f"{arr[i]:.16e}" for arr in arrays)
            if dim == 3:
                f.write(f"    {x[i]:.16e} {y[i]:.16e} {z[i]:.16e} {vals}\n")
            else:
                f.write(f"    {x[i]:.16e} {y[i]:.16e} {vals}\n")
        f.write("  </POINTS>\n")
        f.write("</NEKTAR>\n")


def resolve_fieldconvert(explicit: Path | None = None) -> Path:
    if explicit is not None:
        return explicit

    cands = [
        Path("build/dist/bin/FieldConvert"),
        Path("build/utilities/FieldConvert/FieldConvert"),
        Path("FieldConvert"),
    ]
    for p in cands:
        if p.exists() and os.access(p, os.X_OK):
            return p

    if shutil_which := _which("FieldConvert"):
        return Path(shutil_which)

    raise FileNotFoundError(
        "FieldConvert not found. Build Nektar++ or pass --fieldconvert explicitly."
    )


def _which(cmd: str) -> str | None:
    try:
        proc = subprocess.run(["which", cmd], capture_output=True, text=True, check=False)
    except Exception:
        return None
    out = proc.stdout.strip()
    return out or None


def convert_pts_to_fld(fieldconvert: Path, case_xml: Path, pts_file: Path, fld_file: Path) -> None:
    fld_file.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        str(fieldconvert),
        "-m",
        f"pointdatatofld:frompts={pts_file}",
        str(case_xml),
        str(fld_file),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(
            f"FieldConvert failed for {pts_file}\n"
            f"cmd: {' '.join(cmd)}\n"
            f"stdout:\n{proc.stdout}\n"
            f"stderr:\n{proc.stderr}"
        )


def build_manifest(manifest_path: Path, sample_files: list[Path]) -> None:
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    base = manifest_path.parent.resolve()
    with manifest_path.open("w", encoding="utf-8") as f:
        f.write("# DO init IC sample files (.fld), one per line\n")
        f.write("# Generated by py_utils/ic_sampler/generate_ic_samples.py\n")
        for p in sample_files:
            rel = os.path.relpath(p.resolve(), start=base)
            f.write(f"{Path(rel).as_posix()}\n")
